title = "TiKV"
baseURL = "https://tikv.netlify.com"
languageCode = "en-us"

[params]
description = "A distributed transactional key-value database"
favicon = "tikv-favicon.png"

[params.font]
family = "Titillium Web"
sizes  = [300, 400, 600, 700]

[params.logos]
navbar = "horizontal/color/tikv-horizontal-color.png"
