title = "TiKV"
baseURL = "https://tikv.netlify.com"
languageCode = "en-us"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
description = "A distributed transactional key-value database"
favicon = "tikv-favicon.png"

[params.font]
family = "Titillium Web"
sizes  = [300, 400, 600, 700]

[params.logos]
navbar = "horizontal/color/tikv-horizontal-color.png"
home = "horizontal/black/tikv-horizontal-black.png"

[params.assets]
js = ["jquery-3.3.1"]
