title = "TiKV"
baseURL = "https://tikv.netlify.com"
languageCode = "en-us"

[params]
description = "A distributed transactional key-value database"

[params.font]
family = "Titillium Web"
sizes  = [300, 400, 600, 700]
